In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from fredapi import Fred
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("data.csv", sep=";", decimal=",")
df = df.rename(columns={
    "Column1": "Date",
    "Column2": "SPX",
    "Column3": "S5SFTW",
    "Column4": "S5PHRM",
    "Column5": "S5CPGS",
    "Column6": "S5ENRSX",
    "Column7": "S5FDBT",
    "Column8": "S5TECH",
    "Column9": "S5RETL",
    "Column10": "S5BANKX",
    "Column11": "S5HCES",
    "Column12": "S5DIVF",
    "Column13": "S5UTILX",
    "Column14": "S5MEDA",
    "Column15": "S5REAL",
    "Column16": "S5TELSX",
    "Column17": "S5MATRX",
    "Column18": "S5INSU",
    "Column19": "S5FDSR",
    "Column20": "S5HOUS",
    "Column21": "S5SSEQX",
    "Column22": "S5TRAN",
    "Column23": "S5HOTR",
    "Column24": "S5CODU",
    "Column25": "S5AUCO",
    "Column26": "S5COMS",
})
df["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")

In [64]:
def GetReturn(df,date,lookback):
    date=pd.to_datetime(date)
    if date not in df["Date"].values:#add breaker if windows not in df
        raise ValueError("Date not in dataframe")
    returns_df = df[["Date","S5SFTW","S5PHRM","S5CPGS","S5ENRSX","S5FDBT","S5TECH","S5RETL","S5BANKX","S5HCES","S5DIVF","S5UTILX","S5MEDA","S5REAL","S5TELSX","S5MATRX","S5INSU","S5FDSR","S5HOUS","S5SSEQX","S5TRAN","S5HOTR","S5CODU","S5AUCO","S5COMS"]].copy()

    date_index = returns_df.index[returns_df["Date"] == date][0]
    returns_df=returns_df[(returns_df.index<=date_index) & (returns_df.index>=date_index-lookback) ]
    returns_df.drop(columns="Date",inplace=True)

    returns_df = np.log(returns_df/ returns_df.shift(1))
    returns_df.dropna(inplace=True)
    #print(returns_df.std().mean()) #verification if std is around 1% daily

    return returns_df

#return a df of size (lookback, number of sectors) with log returns


def GetReturnSPX(df,date,lookback):
    date=pd.to_datetime(date)
    if date not in df["Date"].values:#add breaker if windows not in df
        raise ValueError("Date not in dataframe")
    returns_df = df[["Date","SPX"]].copy()

    date_list=returns_df.drop(columns="Date")
    date_index = returns_df.index[returns_df["Date"] == date][0]

    returns_df=returns_df[(returns_df.index<=date_index) & (returns_df.index>=date_index-lookback) ]
    returns_df.drop(columns="Date",inplace=True)

    returns_df = np.log(returns_df/ returns_df.shift(1))
    returns_df.dropna(inplace=True)
    #print(returns_df.std().mean()) #verification if std is around 1% daily

    return returns_df

#return a df of size (lookback, 1) with log returns of SPX

In [65]:
def GetSigma(df,date,lookback):

    returns_df=GetReturn(df,date,lookback=lookback)
    #covariance matric from returns_df
    sigma_windowed=returns_df.cov()

    return sigma_windowed

from sklearn.covariance import LedoitWolf,OAS
import pandas as pd

def get_shrunk_covariance(df,date,lookback):

    returns=GetReturn(df,date,lookback)

    lw = OAS()
    lw.fit(returns)
    shrunk_cov = lw.covariance_

    delta = lw.shrinkage_
    if isinstance(returns, pd.DataFrame):
        shrunk_cov = pd.DataFrame(
            shrunk_cov,
            index=returns.columns,
            columns=returns.columns
        )


    return shrunk_cov


def getSigmaModified(df,date,lookback,listofbanneddays,periodison=False):

    date=pd.to_datetime(date)
    if date not in df["Date"].values:#add breaker if windows not in df
        raise ValueError("Date not in dataframe")
    returns_df = df[["Date","S5SFTW","S5PHRM","S5CPGS","S5ENRSX","S5FDBT","S5TECH","S5RETL","S5BANKX","S5HCES","S5DIVF","S5UTILX","S5MEDA","S5REAL","S5TELSX","S5MATRX","S5INSU","S5FDSR","S5HOUS","S5SSEQX","S5TRAN","S5HOTR","S5CODU","S5AUCO","S5COMS"]].copy()

    date_index = returns_df.index[returns_df["Date"] == date][0]
    returns_df=returns_df[(returns_df.index<=date_index) & (returns_df.index>=date_index-lookback)]
    #days selection

    #banned days
    for banned_date in listofbanneddays:
        mask = returns_df["Date"] == banned_date
        if mask.any():
            print("got one :", banned_date)
            returns_df.loc[mask, :] = np.nan

    returns_df.drop(columns="Date",inplace=True)
    returns_df.dropna(inplace=True)

    #calculation of returns
    returns_df = np.log(returns_df/ returns_df.shift(1))
    returns_df.dropna(inplace=True)

    #covaraicne matrix using shrinkage
    lw = OAS()
    lw.fit(returns_df)
    shrunk_cov = lw.covariance_

    delta = lw.shrinkage_
    if isinstance(returns_df, pd.DataFrame):
        shrunk_cov = pd.DataFrame(
            shrunk_cov,
            index=returns_df.columns,
            columns=returns_df.columns
        )


    return shrunk_cov

#return a cov matrix of size (number of sectors, number of sectors) we use lookback to have different window sizes

In [66]:
def GetRfDataframe(df):
    fred = Fred(api_key="5c742a53d96bd3085e9199dcdb5af60b")
    riskfree = fred.get_series('DFF')
    # riskfree = fred.get_series('DTB1MO')

    riskfree = riskfree.to_frame(name='FedFunds')
    riskfree.index.name = "Date"
    riskfree = riskfree[riskfree.index >= "2002-01-01"]
    riskfree["FedFunds"]=riskfree["FedFunds"]/100
    list_days_open = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")
    list_days_full = pd.to_datetime(riskfree.index, dayfirst=True, errors="coerce")

    list_days_open=[pd.to_datetime(date) for date in list_days_open]
    list_days_full=[pd.to_datetime(date) for date in list_days_full]


    list_days_open_pondered=[]
    riskfree_list=[]
    count_list=[]
    timestamp=0
    while timestamp < len(list_days_full)-1:

      if list_days_full[timestamp+1] in list_days_open:
            list_days_open_pondered.append(list_days_full[timestamp])
            riskfree_list.append(riskfree["FedFunds"].loc[list_days_full[timestamp]])
            count_list.append(1)
            timestamp += 1

      else:
          count = 0
          timestampbis = timestamp
          while (timestamp + 1 < len(list_days_full)) and (list_days_full[timestamp + 1] not in list_days_open):
              timestamp += 1
              count += 1

          list_days_open_pondered.append(list_days_full[timestampbis])  # jour de départ
          riskfree_list.append(riskfree["FedFunds"].loc[list_days_full[timestampbis]])
          count_list.append(count+1)
          timestamp += 1

    RfDf=pd.DataFrame({"Date":list_days_open_pondered,"Rf":riskfree_list,"Count":count_list})
    RfDf=RfDf.set_index("Date")
    return RfDf

def GetRiskFree(df,date,lookback,RfDf):
    positionOfStartDate=df.index[df["Date"]==pd.to_datetime(date)][0]-lookback
    #print(positionOfStartDate)
    startDate=pd.to_datetime(df.iloc[positionOfStartDate,0])
    endDate=pd.to_datetime(date)
    RfDf=RfDf[(RfDf.index >= startDate) & (RfDf.index <= endDate )].copy()
    CumulativeRf=[]

    for i in range(len(RfDf)):
      if i==0:
        CumulativeRf.append(pow((1+RfDf["Rf"].iloc[i]),(RfDf["Count"].iloc[i]/360)))
      else:
        CumulativeRf.append(pow((1+RfDf["Rf"].iloc[i]),(RfDf["Count"].iloc[i]/360))*CumulativeRf[i-1])

    RfDf["CumulativeRf"]=CumulativeRf
    RfDf["CumulativeRf"]= RfDf["CumulativeRf"]-1

    return RfDf["CumulativeRf"].iloc[-1]

RfDf=GetRfDataframe(df)

#compute risk free dataframe using API from FRED and get the cumulative risk free rate between two dates in a df

In [67]:
def GetWeight(df,date):
    #for the moment we will use the equal weight
    weight_vector=np.zeros((24,1))
    for i in range(0,24):
        weight_vector[i]=1/24

    return weight_vector

#usual weighting scheme, for the moment equal weight

In [68]:
def GetLambda(df,date,timeofcalculation,RfDf):
    returns=GetReturn(df,date,timeofcalculation) #daily returns
    weight_vector=GetWeight(df=0,date=0)

    mean_return=np.mean(np.dot(returns,weight_vector))
    mean_annual=(1+mean_return)**252-1 #annualized mean return


    rf_temps=GetRiskFree(df,date,timeofcalculation,RfDf)
    rf_annual=(1+rf_temps)**(252/timeofcalculation)-1 #annualized risk free rate


    Sigma=get_shrunk_covariance(df,date,timeofcalculation)
    Sigma_annual=252*Sigma #annualized covariance matrix
    var = float((weight_vector.T @ Sigma_annual.values @ weight_vector).item())
    lambda_value=(mean_annual - rf_annual)/var


    excess = mean_annual - rf_annual
    sigma2 = var
    sigma  = np.sqrt(var)
    lam    = excess / sigma2
    sharpe = excess / sigma
    #print("Excess:", excess, " Var:", sigma2, " Vol:", sigma, " λ:", lam, " Sharpe:", sharpe)

    return lambda_value

#compute the lambda value using the mean return, risk free rate and variance of the portfolio

Lambda=GetLambda(df,"2024-01-11",timeofcalculation=3500,RfDf=RfDf)

In [69]:
#add the Q matrix calculation

def QMatrixCalculation(df,date,lookback,proportion,performerc_daily,dailyperf_market,historical_returns):
    Q=np.zeros((proportion,1))
    factor=1
    for i in range(proportion):
        Q[i,0]=(performerc_daily[i][0]-dailyperf_market)/2


    return Q,historical_returns

In [229]:
def GetPMatrix(df,date, lookback,proportion=3,historical_returns=0):

    AssetColumns=["S5SFTW","S5PHRM","S5CPGS","S5ENRSX","S5FDBT","S5TECH","S5RETL","S5BANKX","S5HCES","S5DIVF","S5UTILX","S5MEDA","S5REAL","S5TELSX","S5MATRX","S5INSU","S5FDSR","S5HOUS","S5SSEQX","S5TRAN","S5HOTR","S5CODU","S5AUCO","S5COMS"]
    bestperformer = []
    performerc = []
    performerc_daily=[]
    returnBestPerformer=[]
    endDateIndex=df.index[df["Date"]==pd.to_datetime(date)][0]
    startDateIndex=df.index[df["Date"]==pd.to_datetime(date)][0]-lookback

    for i in range(2, df.shape[1]):  #loop through asset columns
        performerc.append((((float(df.iloc[endDateIndex, i]) / float(df.iloc[startDateIndex, i]) - 1) * 100), i - 2,df.columns[i])) #pos of best stock in a tuple
        # with its return
        performerc_daily.append(((float(df.iloc[endDateIndex, i]) / float(df.iloc[startDateIndex, i])) ** (1/lookback) - 1, i - 2,df.columns[i])) #daily version


    performerc.sort(reverse=True)
    performerc_daily.sort(reverse=True)
    #print(performerc)
    perfMarket= (float(df.iloc[endDateIndex, 1]) / float(df.iloc[startDateIndex, 1]) - 1) * 100
    dailyperf_market = (float(df.iloc[endDateIndex, 1]) / float(df.iloc[startDateIndex, 1])) ** (1/lookback) - 1






    for i in range(proportion):
        bestperformer.append(performerc_daily[i][1])
        returnBestPerformer.append(performerc_daily[i][0])


    P=np.zeros((proportion,24))
    Q=np.zeros((proportion,1))
    for lineview in range(proportion):
        for i in range(len(AssetColumns)):
            P[lineview,i]=-1/len(AssetColumns)
        P[lineview,bestperformer[lineview]]=1-1/len(AssetColumns)
        sum=0
        for i in range(len(AssetColumns)):
            sum+=P[lineview,i]
    Q,historical_returns=QMatrixCalculation(df,date,lookback,proportion,performerc_daily,dailyperf_market,historical_returns)


    return P, Q, historical_returns

In [71]:
def GetOmega(PMatrix, Sigma, c=0.99):
    #Omega is the uncertainty of the views

    factorC=(1/c-1)
    Omega=factorC*PMatrix@Sigma@np.transpose(PMatrix)

    return Omega

In [72]:
def LinkOmegaTau(Omega, Sigma, P):
    #Link omega to tau
    constant=36

    multiple= np.trace(np.transpose(P) @ np.linalg.inv(Omega) @ P) * constant
    numerator= np.trace(np.linalg.inv(Sigma*252))

    result= numerator / multiple
    return result

In [73]:
def LinkOmegaTau2(Omega, Sigma,P,tau):
    #Link omega to tau
    numerator= np.trace(np.linalg.inv(Sigma*tau))
    denominator= np.trace((np.transpose(P)@np.linalg.inv(Omega)@P))
    result=numerator/denominator

    return result

In [246]:
def BlackAndLittermanModel(backtestStartDate, rebalancingFrequency, lookbackPeriod, df,RfDf,confidence=0.75,proportion=4,tau=0.025,Lambda=3,historical_returns=0,modifiedlambda=0):
    #implement the full backtest of the black and litterman model

    #---------
    #PARAMETERS
    #---------
    datetoremove=pd.to_datetime("2018-04-06") #add date to remove
    listofbanneddays=[]
    Sigma=get_shrunk_covariance(df,backtestStartDate,lookback=60) #using 720 days to have better sigma of 2 years
    Sigma=getSigmaModified(df,backtestStartDate,lookback=60,listofbanneddays=listofbanneddays) #using 720 days to have better sigma of 2 years


    PMatrix,Q,historical_returns= GetPMatrix(df,backtestStartDate, lookback=lookbackPeriod,proportion=proportion,historical_returns=historical_returns)
    Omega=GetOmega(PMatrix, Sigma, c=confidence)
    rf=GetRiskFree(df,backtestStartDate,lookbackPeriod,RfDf)
    weights = GetWeight(df, backtestStartDate)
    weights = np.array(weights).reshape(-1, 1)

    changingLambda=True
    if changingLambda==True:
        if pd.to_datetime(backtestStartDate) < pd.to_datetime("2006-04-06"):
            Lambda=3
        else :
            Lambda=3#+0.1*GetLambda(df,backtestStartDate,timeofcalculation=504,RfDf=RfDf)
    else :
        Lambda=3

    uimplied = Lambda * (Sigma @ weights) + rf
    #BL formula
    #tau=OmegaLinked




    optimizedReturn=(np.linalg.inv(np.linalg.inv(tau*Sigma)+np.transpose(PMatrix)@np.linalg.inv(Omega)@PMatrix)) @ (np.linalg.inv(tau*Sigma)@uimplied+np.transpose(PMatrix)@np.linalg.inv(Omega)@Q)
    LambdaMarkowitz=3

    #MarkowitzAllocation
    WeightBL=np.linalg.inv(Sigma)@(optimizedReturn-rf)/LambdaMarkowitz
    WeightRF=1-np.sum(WeightBL)
    #if not np.isclose(float(np.sum(WeightBL)), 1.0, atol=1e-6):
        #print(np.sum(WeightBL))
        #raise ValueError("Weights do not sum to 1, please investigate.")

    return WeightBL,WeightRF,historical_returns


BlackAndLittermanModel("2018-05-11", rebalancingFrequency=3, lookbackPeriod=180, df=df,RfDf=RfDf)

bestperf: [6, 18, 3, 0]
returns: [0.0018400869311319124, 0.0013745001945468793, 0.0010811945365682973, 0.0010262579908977276]

(           0
 0  -0.013340
 1   0.032326
 2   0.032326
 3   0.103074
 4   0.032326
 5   0.032326
 6   0.222422
 7   0.032326
 8   0.032326
 9   0.032326
 10  0.032326
 11  0.032326
 12  0.032326
 13  0.032326
 14  0.032326
 15  0.032326
 16  0.032326
 17  0.032326
 18  0.041334
 19  0.032326
 20  0.032326
 21  0.032326
 22  0.032326
 23  0.032326,
 0   -1.172396e-13
 dtype: float64,
 0)

In [230]:
from rich.console import Console
from rich.panel import Panel
from tqdm import tqdm

console = Console()

#BACK TESTER
dfbacktest=df.copy()
dfbacktest["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
dfbacktest["MonthIndex"] = dfbacktest["Date"].dt.to_period("M")

df_length = dfbacktest.shape[1] - 2  # bcs of date and spx
last_rebalance = dfbacktest.loc[0, "Date"]  # première date
month_count = 0

# 🎨 AFFICHAGE STYLÉ (sans prompts)
hold = 1
hist = 0
proportion = 4
Lambda=3
tau=0.025
confidence=0.75

console.print(Panel.fit(
    "[bold cyan]📊 PORTFOLIO BACKTESTER[/bold cyan]\n"
    "[dim]Black-Litterman Model[/dim]",
    border_style="cyan"
))

console.print(f"\n[yellow]⚙️  Configuration :[/yellow]")
console.print(f"   • Hold period: [cyan]{hold}[/cyan] mois")
console.print(f"   • Historique: [cyan]{hist}[/cyan] mois")
console.print(f"   • Proportion: [cyan]{proportion}[/cyan]")
console.print(f"   • Lambda: [cyan]{Lambda:.4f}[/cyan]")
console.print(f"   • Confiance: [cyan]{confidence}[/cyan]")
console.print(f"   • Taux: [cyan]{tau}[/cyan]\n")

console.print("\n[yellow]⏳ Lancement du backtest...[/yellow]\n")

def Backtester(df,hold, hist, proportion,df_toBL, RfDf,confidence2,proportion2,tau2,Lambda2,start,modifiedlambda):
    #new dataframe for stock quantity

    StockQty = df.copy()
    StockQty.drop(columns="MonthIndex", inplace=True)
    historical_returns=[]

    StockQty.loc[:, :] = 0
    #starting data
    MoneyAtStart = 10000000
    month_count=0
    CurrentValue=MoneyAtStart
    spaceindays=0
    #first ligne
    StockQty.loc[start, "Money"] = MoneyAtStart
    StockQty.loc[start, "SPX"] = df.iloc[start, 1]
    StockQty.loc[start, "Date"] = df.iloc[start, 0]
    RiskFreeAmount=0
    #start of the algorithm

    for i in tqdm(range(start,df.shape[0]), desc="Backtesting"):
      StockQty.iloc[i,0]=df.iloc[i,0]
      StockQty.iloc[i,1]=df.iloc[i,1]
      fees=0


      if df.loc[i, "Date"].month != df.loc[i-1, "Date"].month:
        month_count += 1


    # Si on atteint la période voulue
      if i>= hist and spaceindays>21*hold:
        #print(f"🔁 Rebalancement déclenché à la date : {df.loc[i, 'Date'].date()}")
        #print(str(df.iloc[i,0]))

        spaceindays=0

        BLWeight,RiskFreeAmount,historical_returns=BlackAndLittermanModel(str(df.iloc[i,0]),3,3*22,df_toBL,RfDf,confidence=confidence2,proportion=proportion2,tau=tau2,Lambda=Lambda2,historical_returns=historical_returns,modifiedlambda=modifiedlambda)
        #print(len(BLWeight))
        for index in range(len(BLWeight)):
            StockQty.iloc[i,index+2]=(BLWeight.iloc[index,0]*CurrentValue)/df.iloc[i,index+2] #qty = weight*total value/price
      else :
        spaceindays+=1
        for stocks in range(2,StockQty.shape[1]-1):
          StockQty.iloc[i,stocks]=StockQty.iloc[i-1,stocks] #same qty


      #value of pf

      GainOrLoss = 0
      for stocks in range(2, StockQty.shape[1]-1):
        qty = StockQty.iloc[i, stocks]

        if qty != 0.0:
            price_now = df.iloc[i, stocks]
            price_prev = df.iloc[i-1, stocks]
            GainOrLoss += qty * (price_now - price_prev)

      daily_rate = GetRiskFree(df, str(df.iloc[i,0]), 1, RfDf)
      interest_gain = (CurrentValue * RiskFreeAmount) * daily_rate
      CurrentValue += GainOrLoss + interest_gain - fees
      StockQty.iloc[i,-1]=CurrentValue


    StockQty = StockQty.iloc[start:].reset_index(drop=True)
    return StockQty
RfDf=GetRfDataframe(df)
final = Backtester(dfbacktest, hold=hold, hist=hist, proportion=proportion, df_toBL=df,RfDf=RfDf,confidence2=confidence,proportion2=proportion,tau2=tau,Lambda2=Lambda,start=181,modifiedlambda=0)

console.print("\n[green]✅ Backtest terminé avec succès ![/green]\n")

╭─────────────────────────╮
│ 📊 PORTFOLIO BACKTESTER │
│ Black-Litterman Model   │
╰─────────────────────────╯

⚙️  Configuration :

   • Hold period: 1 mois

   • Historique: 0 mois

   • Proportion: 4

   • Lambda: 3.0000

   • Confiance: 0.75

   • Taux: 0.025

⏳ Lancement du backtest...

Backtesting:   1%|          | 36/5602 [00:00<00:37, 148.14it/s]

bestperf: [1, 8, 17, 11]
returns: [0.0011897477044384708, 0.0007878047562910329, 0.0004643257460907879, -0.0005948674482496585]
bestperf: [11, 13, 0, 6]
returns: [0.0033789715205565507, 0.0024894505484069906, 0.001920616503623629, 0.00085597437670204]

Backtesting:   1%|▏         | 81/5602 [00:00<00:42, 128.91it/s]

bestperf: [13, 0, 5, 18]
returns: [0.0028767691463849054, 0.0016450554393918626, 0.001613293867965604, 0.0015577056222355612]
bestperf: [5, 10, 18, 13]
returns: [0.003844205020135716, 0.0033697101321523704, 0.002997532423627547, 0.0028818382556159428]

Backtesting:   2%|▏         | 124/5602 [00:00<00:42, 128.44it/s]

bestperf: [7, 14, 10, 3]
returns: [-9.375595442329132e-05, -0.00018077129725746488, -0.00031233021198373567, -0.0003125035752624683]
bestperf: [18, 5, 6, 20]
returns: [0.0018395936858808248, 0.0012160278510207068, 0.0010336127540568896, 0.0008295032507583677]

Backtesting:   3%|▎         | 181/5602 [00:01<00:41, 130.30it/s]

bestperf: [18, 6, 12, 5]
returns: [0.0030342008365507045, 0.002110896382135241, 0.001670505892855445, 0.0014061998096686068]
bestperf: [10, 20, 6, 9]
returns: [0.0030786340576367532, 0.002544083684709708, 0.002451927613153382, 0.0024266564803077095]

Backtesting:   4%|▍         | 223/5602 [00:01<00:41, 128.30it/s]

bestperf: [20, 9, 10, 23]
returns: [0.0032607664771902023, 0.003084742867477175, 0.0028998878951014273, 0.0026228829257495256]
bestperf: [18, 20, 23, 9]
returns: [0.0032128011365726294, 0.002729997937686246, 0.0024456306664977223, 0.0023047738905053183]

Backtesting:   5%|▍         | 264/5602 [00:02<00:43, 123.48it/s]

bestperf: [18, 22, 6, 20]
returns: [0.003756511050763578, 0.002543387045732315, 0.0025344035879377724, 0.0021616293475754667]
bestperf: [18, 22, 20, 5]
returns: [0.003268758868907984, 0.0017538991504224555, 0.0015886253291592656, 0.0014250668992601412]

Backtesting:   6%|▌         | 319/5602 [00:02<00:41, 126.95it/s]

bestperf: [18, 6, 5, 21]
returns: [0.0043946062938922115, 0.002301657681916369, 0.00229513927579994, 0.001904088731274678]
bestperf: [18, 20, 5, 14]
returns: [0.0024237689920798555, 0.0017010807662638516, 0.001484590506784178, 0.001468972766948129]

Backtesting:   6%|▋         | 360/5602 [00:02<00:41, 125.49it/s]

bestperf: [22, 14, 18, 23]
returns: [0.003433026747261092, 0.0026023208582568458, 0.002263974652106926, 0.001854449908210709]
bestperf: [13, 15, 22, 3]
returns: [0.002383998818306088, 0.002267520650560906, 0.0021665448447838465, 0.0021157660177235638]

Backtesting:   7%|▋         | 400/5602 [00:03<00:43, 120.83it/s]

bestperf: [13, 15, 3, 20]
returns: [0.0020743646436738317, 0.00198308912528522, 0.001955231510754718, 0.0018778790337430351]

Backtesting:   8%|▊         | 428/5602 [00:03<00:42, 122.67it/s]

bestperf: [20, 8, 15, 17]
returns: [0.0018989568717837635, 0.0016483543292840075, 0.0014499323717920287, 0.0012393835076218718]
bestperf: [17, 8, 3, 23]
returns: [0.000731118716106538, 0.00038852359190744146, 0.00025208473857274427, -0.00017360132064991873]

Backtesting:   8%|▊         | 470/5602 [00:03<00:42, 121.58it/s]

bestperf: [22, 17, 0, 2]
returns: [0.0015709645234958103, 0.0014430177974245062, 0.0012286846677374008, 0.0011944398109720034]
bestperf: [12, 3, 2, 7]
returns: [0.0010553717618950742, 0.0009596989687259416, 0.0009222172130352035, 0.0007455043617183854]

Backtesting:   9%|▉         | 525/5602 [00:04<00:40, 125.54it/s]

bestperf: [12, 10, 14, 2]
returns: [0.0015026563483981903, 0.0014852096239330592, 0.0011271773259120543, 0.001026725538970652]
bestperf: [3, 10, 13, 12]
returns: [0.001185071027438367, 0.0009715120185798121, 0.0009550557971242934, 0.0008751911799902423]

Backtesting:  10%|█         | 566/5602 [00:04<00:40, 123.00it/s]

bestperf: [6, 3, 13, 19]
returns: [0.0016255591967040406, 0.00150393613164157, 0.0014545176626461487, 0.0013149244152490525]
bestperf: [6, 20, 19, 3]
returns: [0.0026155154907470113, 0.002569034922498492, 0.0025193992993368663, 0.002477812035921678]

Backtesting:  11%|█         | 608/5602 [00:04<00:40, 123.13it/s]

bestperf: [20, 19, 12, 5]
returns: [0.002961962920896788, 0.0026156578077851655, 0.0021864481793334445, 0.0020989025362943003]
bestperf: [8, 4, 20, 15]
returns: [0.002175818294874343, 0.0018182490909737226, 0.001533750495854136, 0.00137144541701395]

Backtesting:  12%|█▏        | 665/5602 [00:05<00:38, 129.66it/s]

bestperf: [3, 8, 4, 21]
returns: [0.0025460676828885642, 0.0014188492875659708, 0.0009141340947234067, 0.0008783901542688266]
bestperf: [3, 10, 8, 17]
returns: [0.00237990546192135, 0.0005978336242251636, 0.0004235951773774449, 0.00023283345095670427]

Backtesting:  13%|█▎        | 707/5602 [00:05<00:37, 129.93it/s]

bestperf: [1, 12, 3, 10]
returns: [0.0011217175731035312, 0.001097450376033482, 0.00106848917384883, 0.000794905690385761]
bestperf: [12, 18, 10, 8]
returns: [0.0009751649062543777, 0.0008232312355054283, 0.0005872367417469881, 0.0005025855789233535]

Backtesting:  13%|█▎        | 747/5602 [00:06<00:39, 122.91it/s]

bestperf: [12, 18, 15, 10]
returns: [0.0021140296163864036, 0.0016027470107511377, 0.0015198270891314536, 0.00093213306209039]
bestperf: [3, 6, 18, 22]
returns: [0.0020852322012017144, 0.001939918404467278, 0.0019266466418275119, 0.0016403635068489297]

Backtesting:  14%|█▍        | 801/5602 [00:06<00:38, 125.89it/s]

bestperf: [3, 10, 8, 5]
returns: [0.0024489347868574818, 0.0011868085246724558, 0.0008494250254427183, 0.0008237201087275547]
bestperf: [3, 19, 4, 5]
returns: [0.0007572060606690911, 0.0007010185934697155, 0.0002973796176313215, 9.617203869627389e-05]

Backtesting:  15%|█▌        | 843/5602 [00:06<00:38, 122.33it/s]

bestperf: [9, 19, 15, 4]
returns: [0.0013631235214857096, 0.001236944385607508, 0.0012121427991285127, 0.000424059504012142]
bestperf: [19, 9, 14, 15]
returns: [0.002253593086525285, 0.0015558530461832198, 0.0013569241505739793, 0.0012992304407450916]

Backtesting:  16%|█▌        | 885/5602 [00:07<00:37, 125.26it/s]

bestperf: [14, 9, 18, 5]
returns: [0.002304610320574385, 0.0020158823596048148, 0.0020077509843829944, 0.0018120986304381859]
bestperf: [13, 19, 20, 14]
returns: [0.001709379965952218, 0.0015461529776918947, 0.0015150709945443985, 0.0014256086765240816]

Backtesting:  17%|█▋        | 942/5602 [00:07<00:35, 131.95it/s]

bestperf: [12, 19, 13, 5]
returns: [0.0019903403861321056, 0.00168583807221645, 0.0014862427033444092, 0.0011424763946381589]
bestperf: [19, 14, 2, 9]
returns: [0.0018209196709262354, 0.0017216438557512426, 0.0012188085503934687, 0.0010275677136664108]

Backtesting:  18%|█▊        | 984/5602 [00:07<00:35, 131.13it/s]

bestperf: [11, 4, 2, 23]
returns: [0.000638374369807293, 0.0006279504989197271, 0.0005981000017709626, 0.0005372690905220967]
bestperf: [11, 22, 10, 4]
returns: [0.0006469717483084114, 0.0001774269433232334, 0.00012076720495901583, 0.00010915232369379524]

Backtesting:  18%|█▊        | 1027/5602 [00:08<00:34, 131.60it/s]

bestperf: [10, 4, 12, 13]
returns: [0.0014194892186372154, 0.0010904712384283144, 0.0010442525681044756, 0.0008416533918478297]
bestperf: [12, 13, 10, 1]
returns: [0.001448360998993481, 0.0013784234108034088, 0.0013625053821664235, 0.0011720403131294521]

Backtesting:  19%|█▉        | 1067/5602 [00:08<00:40, 112.71it/s]

bestperf: [22, 1, 12, 13]
returns: [0.001761166487783461, 0.001724807138494544, 0.001499828943593462, 0.0014833590973515332]

Backtesting:  19%|█▉        | 1091/5602 [00:08<00:43, 104.70it/s]

bestperf: [5, 0, 6, 22]
returns: [0.0026534851961386163, 0.0026049959028895397, 0.0024165850550292856, 0.0023543139348338737]

Backtesting:  20%|█▉        | 1115/5602 [00:09<00:41, 109.19it/s]

bestperf: [12, 21, 20, 6]
returns: [0.0024201883854566564, 0.0024038721669936702, 0.0022543691585006354, 0.0020445050414974464]

Backtesting:  20%|██        | 1141/5602 [00:09<00:39, 111.56it/s]

bestperf: [11, 14, 21, 5]
returns: [0.001849036089018652, 0.0015140558766923995, 0.0013138535285643904, 0.001238727146824825]
bestperf: [12, 21, 14, 8]
returns: [0.0026283448425803435, 0.0014246502901598124, 0.0014066061298596555, 0.0013375810493230222]

Backtesting:  21%|██        | 1181/5602 [00:09<00:37, 116.71it/s]

bestperf: [22, 8, 14, 13]
returns: [0.001012902883611, 0.0008480599270754841, 0.000790853089097876, 0.0007285926561155787]
bestperf: [10, 14, 3, 13]
returns: [0.001884997942672939, 0.0016649783660178663, 0.0016010790471345793, 0.001351812729978752]

Backtesting:  22%|██▏       | 1239/5602 [00:10<00:33, 130.89it/s]

bestperf: [10, 3, 13, 18]
returns: [0.0016319054113085318, 0.001618413145531017, 0.0014008020892968265, 0.0012974705881438897]
bestperf: [3, 22, 2, 13]
returns: [0.0030289063416413242, 0.0018139784051540708, 0.0017525872108443696, 0.0017357189557789532]

Backtesting:  23%|██▎       | 1279/5602 [00:10<00:36, 120.03it/s]

bestperf: [18, 5, 2, 3]
returns: [0.002781388931700768, 0.002163939914898716, 0.0021637873207429603, 0.002016055019844476]
bestperf: [5, 3, 2, 18]
returns: [0.00046171898889380003, 0.0002474510644554506, 0.0002139229842488266, 0.00016832952188838846]

Backtesting:  24%|██▍       | 1332/5602 [00:10<00:33, 126.36it/s]

bestperf: [17, 3, 5, 2]
returns: [0.0011436429028979234, 0.0010099951774138471, 0.0009219389549406376, 0.000683380590602134]
bestperf: [17, 0, 5, 4]
returns: [0.0015061778454918962, 0.0005752969028882671, 0.0005350192429385281, 0.00045340062773724377]

Backtesting:  25%|██▍       | 1374/5602 [00:11<00:32, 129.68it/s]

bestperf: [0, 17, 3, 10]
returns: [0.001564498681889459, 0.0015605034724079925, 0.0009475497534983113, 0.0009429065546531223]
bestperf: [0, 4, 17, 10]
returns: [0.0017108956193689906, 0.0011697727594985885, 0.0009925112165176664, 0.0009559401675209855]

Backtesting:  25%|██▌       | 1414/5602 [00:11<00:34, 120.54it/s]

bestperf: [8, 4, 16, 19]
returns: [-0.00027723799060197507, -0.0005955267217294669, -0.0006733201685870105, -0.0009300279866999439]
bestperf: [14, 3, 19, 16]
returns: [0.001251360218403219, 0.0010463208677884417, 0.0006910716047050514, 0.00011998327547946275]

Backtesting:  26%|██▌       | 1470/5602 [00:11<00:31, 129.90it/s]

bestperf: [19, 12, 16, 21]
returns: [0.0007248609647689808, 0.000420237232909626, 3.7178618192745816e-05, -8.281647824581739e-05]
bestperf: [19, 12, 3, 16]
returns: [0.0019530661040649822, 0.0019200425540182309, 0.0018497162997104244, 0.0018018282691458776]

Backtesting:  27%|██▋       | 1512/5602 [00:12<00:31, 129.18it/s]

bestperf: [19, 5, 18, 0]
returns: [0.0020249710848248004, 0.0019084943280922584, 0.001744267435273672, 0.0016047834977321873]
bestperf: [3, 10, 5, 16]
returns: [0.00136064052802376, 0.0005120349607503627, -5.814723684383072e-05, -0.0001308117618045168]

Backtesting:  28%|██▊       | 1556/5602 [00:12<00:31, 130.00it/s]

bestperf: [1, 17, 8, 4]
returns: [0.0005949239606446444, 0.0002516602936728507, 0.0002439774960409924, 0.00011405665549868438]
bestperf: [17, 6, 1, 4]
returns: [0.0015126026173886142, 0.0011895020551329072, 0.0006363239690074796, 0.0004143670909044772]

Backtesting:  29%|██▊       | 1597/5602 [00:12<00:32, 124.86it/s]

bestperf: [17, 7, 4, 21]
returns: [-0.0008688771426084152, -0.0023417941948675747, -0.0023484571843999102, -0.0024773090043824775]

Backtesting:  29%|██▉       | 1625/5602 [00:13<00:31, 124.95it/s]

bestperf: [17, 16, 4, 1]
returns: [-0.001917429286555028, -0.0029267446295503374, -0.0030680139190947253, -0.0031247211885319093]
bestperf: [13, 1, 10, 16]
returns: [-0.002471391425994729, -0.0026140787633756046, -0.0033521151028942375, -0.003404491468876558]

Backtesting:  30%|██▉       | 1664/5602 [00:13<00:32, 120.45it/s]

bestperf: [1, 10, 20, 13]
returns: [-0.00012693352419390624, -0.0002924807657569417, -0.0005138255446219819, -0.0006157508018337365]
bestperf: [5, 8, 6, 20]
returns: [0.0013341022939232783, 0.0012066166831667946, 0.0008876145482632491, 0.0008279122323169297]

Backtesting:  31%|███       | 1721/5602 [00:13<00:30, 128.96it/s]

bestperf: [18, 5, 0, 6]
returns: [0.00019423979298749394, 2.5095997906232625e-05, -0.00047246221944807765, -0.0007070077584599987]
bestperf: [9, 22, 6, 5]
returns: [0.003424895813945339, 0.0029821822355136085, 0.0024720184588675753, 0.0023733484552757034]

Backtesting:  31%|███▏      | 1760/5602 [00:14<00:31, 123.48it/s]

bestperf: [22, 7, 9, 15]
returns: [0.0099220392578383, 0.008599154518162067, 0.007245389201975261, 0.004574702754746918]
bestperf: [22, 9, 7, 12]
returns: [0.006716550732979609, 0.004305196142726508, 0.004119561977526942, 0.0035528513435947318]

Backtesting:  32%|███▏      | 1815/5602 [00:14<00:28, 131.26it/s]

bestperf: [22, 18, 11, 9]
returns: [0.003914564504257978, 0.0031638896433523467, 0.0027581623350625417, 0.0027465359165859127]
bestperf: [22, 15, 9, 12]
returns: [0.004835855274899048, 0.003867886946167687, 0.0038643369998421218, 0.003306325424479173]

Backtesting:  33%|███▎      | 1857/5602 [00:15<00:29, 126.39it/s]

bestperf: [12, 15, 22, 21]
returns: [0.004395948805086869, 0.00403623686477772, 0.003725990984381644, 0.003655197364732743]
bestperf: [12, 15, 0, 7]
returns: [0.0020828591789077144, 0.0016099191894765053, 0.001491832865249787, 0.0014514843407433808]

Backtesting:  34%|███▍      | 1898/5602 [00:15<00:30, 122.21it/s]

bestperf: [12, 17, 22, 0]
returns: [0.002936359418450385, 0.0025587482845574883, 0.0024905894008060425, 0.002476035399978427]

Backtesting:  34%|███▍      | 1925/5602 [00:15<00:31, 118.34it/s]

bestperf: [22, 0, 8, 12]
returns: [0.004162270450255745, 0.002722961241546251, 0.0023361905487304657, 0.0022651195520737577]
bestperf: [22, 8, 20, 11]
returns: [0.003906302952223495, 0.0013767803054329786, 0.0011403602032442617, 0.0010993156379397462]

Backtesting:  35%|███▌      | 1963/5602 [00:15<00:32, 113.55it/s]

bestperf: [22, 21, 7, 15]
returns: [0.00361813477584616, 0.001761830729743341, 0.0016092931519680054, 0.0014819460838708665]
bestperf: [7, 20, 12, 6]
returns: [0.0020961341785596943, 0.001817880983775444, 0.0017948857390379658, 0.0017490753459519226]

Backtesting:  36%|███▌      | 2021/5602 [00:16<00:27, 129.35it/s]

bestperf: [12, 7, 19, 21]
returns: [0.003933778398339971, 0.003498854867849177, 0.0029397155001715802, 0.00285971254662698]
bestperf: [12, 20, 11, 21]
returns: [0.0009066734932170473, 0.0007412763205045803, 0.0003751291614231267, 0.0001588779982519828]

Backtesting:  37%|███▋      | 2063/5602 [00:16<00:27, 130.87it/s]

bestperf: [10, 17, 4, 13]
returns: [-2.9632307606553e-06, -0.00017792223020940412, -0.00036612468527863484, -0.0004007355780396571]
bestperf: [13, 10, 12, 4]
returns: [0.0010217083349197686, 0.0004941942076905903, 0.00046707993486472255, 0.00041721864548005527]

Backtesting:  38%|███▊      | 2106/5602 [00:17<00:27, 128.18it/s]

bestperf: [13, 14, 4, 12]
returns: [0.001566479337814508, 0.0011435309079002032, 0.0010244968003549904, 0.0008297079520840356]
bestperf: [19, 13, 22, 6]
returns: [0.00248615521379425, 0.0022289136007531685, 0.002168319275992925, 0.0021528659941796313]

Backtesting:  38%|███▊      | 2148/5602 [00:17<00:27, 126.57it/s]

bestperf: [22, 3, 6, 21]
returns: [0.004464246591796117, 0.0028289895310400492, 0.002684023486003717, 0.002673111368374448]
bestperf: [22, 3, 18, 14]
returns: [0.004252055766969853, 0.0031155976263577134, 0.002465814276576994, 0.002401868655911077]

Backtesting:  39%|███▉      | 2206/5602 [00:17<00:25, 133.18it/s]

bestperf: [22, 7, 3, 18]
returns: [0.0029224468835875594, 0.002702650855036959, 0.002494477713449461, 0.0023187042499257515]
bestperf: [3, 7, 11, 9]
returns: [0.0031352385558427454, 0.002545959943981657, 0.002510430313035217, 0.0022033731477244523]

Backtesting:  40%|████      | 2246/5602 [00:18<00:29, 115.58it/s]

bestperf: [3, 11, 8, 2]
returns: [0.0024738755069213525, 0.0019332028967851134, 0.001479183507283599, 0.0012759081076698653]

Backtesting:  41%|████      | 2272/5602 [00:18<00:28, 116.57it/s]

bestperf: [11, 4, 8, 1]
returns: [0.002183264483758496, 0.0018354606488932834, 0.0018267053412521772, 0.0017956026008327797]
bestperf: [1, 4, 16, 13]
returns: [0.0015229789342050548, 0.0011231744904387497, 0.0010543039723167613, 0.001030926686073963]

Backtesting:  41%|████      | 2309/5602 [00:18<00:29, 111.74it/s]

bestperf: [20, 21, 1, 8]
returns: [0.0014291109314694683, 0.0013124796409129669, 0.001162036896958929, 0.0008156718696938903]
bestperf: [20, 4, 10, 0]
returns: [-0.00015650112013376738, -0.0003129209472116923, -0.0005443863321938913, -0.0007616593948278627]

Backtesting:  42%|████▏     | 2363/5602 [00:19<00:26, 123.13it/s]

bestperf: [6, 20, 10, 4]
returns: [0.00021318047148644048, 0.00020061150400696448, 0.00017528378307241077, 3.937729865710615e-05]
bestperf: [10, 17, 0, 4]
returns: [0.00012674077386232163, -8.127353915354796e-05, -0.0005781925148351519, -0.0006377779225716917]

Backtesting:  43%|████▎     | 2404/5602 [00:19<00:24, 127.95it/s]

bestperf: [21, 6, 10, 16]
returns: [0.0027765379644497656, 0.00209559995511599, 0.001998837980855761, 0.0019173934700942308]
bestperf: [21, 0, 20, 19]
returns: [0.0016108783322634768, 0.0015039670242420478, 0.0014707160504403571, 0.001456430631263217]

Backtesting:  44%|████▍     | 2460/5602 [00:20<00:24, 130.62it/s]

bestperf: [7, 12, 2, 19]
returns: [0.002279655560206262, 0.0019013631404898312, 0.00188890390161367, 0.0017670439414623207]
bestperf: [7, 5, 21, 9]
returns: [0.002342614140536936, 0.0020887995502634205, 0.0019096109839840114, 0.001836824619833699]

Backtesting:  45%|████▍     | 2500/5602 [00:20<00:25, 120.60it/s]

bestperf: [9, 5, 7, 21]
returns: [0.004809293278569493, 0.004512289374810408, 0.0037793555534118006, 0.0034006677257822915]
bestperf: [5, 9, 6, 21]
returns: [0.0026040866615772984, 0.002153731158377692, 0.001793791764201691, 0.0014805958290093901]

Backtesting:  45%|████▌     | 2541/5602 [00:20<00:24, 123.47it/s]

bestperf: [13, 4, 6, 10]
returns: [0.001065450451196659, 0.0006775665320057911, 0.0006674051414410354, 0.0002881501350318061]
bestperf: [13, 10, 16, 1]
returns: [0.0013004355421029068, 0.0007304798716198935, 0.0005342702365602747, 0.0005195534100994603]

Backtesting:  46%|████▋     | 2595/5602 [00:21<00:24, 123.09it/s]

bestperf: [13, 16, 11, 10]
returns: [0.0014600313777575202, 0.0013923267795212801, 0.0008594242504966765, 0.0008117463203640707]
bestperf: [11, 5, 3, 13]
returns: [0.0020122236266606475, 0.0020079039281939437, 0.0014228313399946568, 0.0013650432280074565]

Backtesting:  47%|████▋     | 2638/5602 [00:21<00:23, 125.58it/s]

bestperf: [5, 3, 11, 9]
returns: [0.0020670792160686347, 0.0020048653743118816, 0.0019319579487051541, 0.001700796545622385]
bestperf: [9, 11, 15, 22]
returns: [0.0020621460946539383, 0.0012057050635971844, 0.0011863514176910783, 0.001149888955570555]

Backtesting:  48%|████▊     | 2679/5602 [00:21<00:23, 124.56it/s]

bestperf: [22, 9, 21, 11]
returns: [0.0018240516560192876, 0.0015428067755596242, 0.0008547055449157348, 0.0007545288729833288]
bestperf: [22, 9, 23, 19]
returns: [0.003214021029144698, 0.0020363091256097032, 0.0010644667237627026, 0.0009468861654551297]

Backtesting:  49%|████▉     | 2736/5602 [00:22<00:21, 133.51it/s]

bestperf: [22, 9, 15, 23]
returns: [0.0020792228104229427, 0.001714067406123787, 0.0014136088537868297, 0.0013839767743957232]
bestperf: [9, 22, 11, 19]
returns: [0.0027668528082815946, 0.0023444700713832756, 0.002011029375044604, 0.0019158867176585215]

Backtesting:  50%|████▉     | 2777/5602 [00:22<00:22, 125.14it/s]

bestperf: [1, 17, 11, 16]
returns: [0.002156710203578216, 0.001970552743757681, 0.0019141141398115735, 0.00191269351808665]
bestperf: [11, 1, 21, 18]
returns: [0.0023822445004240134, 0.0020801187140739863, 0.002051904496954693, 0.001879204942083046]

Backtesting:  50%|█████     | 2817/5602 [00:22<00:23, 119.39it/s]

bestperf: [22, 15, 9, 16]
returns: [0.001433968808595143, 0.0011896205064749754, 0.0011475640077764915, 0.0010882572150372471]
bestperf: [22, 7, 9, 6]
returns: [0.002716746529345171, 0.002173845389375817, 0.0018896547870805858, 0.0016724636924834169]

Backtesting:  51%|█████▏    | 2872/5602 [00:23<00:21, 129.01it/s]

bestperf: [5, 22, 7, 2]
returns: [0.0017301337875290645, 0.001452928094435313, 0.0012308532983806852, 0.000616194293687089]
bestperf: [22, 11, 2, 15]
returns: [0.0019209572169509581, 0.0014447793635996575, 0.0012524335087269467, 0.0009872325005737537]

Backtesting:  52%|█████▏    | 2912/5602 [00:23<00:22, 117.03it/s]

bestperf: [14, 5, 2, 1]
returns: [0.001216864908808235, 0.0011478667323407965, 0.001030525720896236, 0.0009838592468334184]
bestperf: [19, 21, 0, 6]
returns: [0.0018496924444457719, 0.0016243170100174176, 0.0016107283030506458, 0.0015824697868473958]

Backtesting:  53%|█████▎    | 2965/5602 [00:24<00:20, 126.18it/s]

bestperf: [5, 19, 0, 11]
returns: [0.0017093709087310227, 0.0016247182175463948, 0.001478277432785946, 0.001432183008053478]
bestperf: [0, 18, 19, 7]
returns: [0.0014816930660903616, 0.0013373438315518182, 0.0012952595113935317, 0.0012872993112875708]

Backtesting:  54%|█████▎    | 3006/5602 [00:24<00:20, 125.33it/s]

bestperf: [0, 1, 18, 12]
returns: [0.00131092804284072, 0.001153660193419892, 0.0010945539983624464, 0.0009730117012463069]
bestperf: [10, 12, 7, 8]
returns: [0.0012580821907788309, 0.0009042162116541519, 0.0008632727435140541, 0.000768010857504775]

Backtesting:  54%|█████▍    | 3046/5602 [00:24<00:21, 121.19it/s]

bestperf: [10, 5, 3, 12]
returns: [0.001838574052131392, 0.0016163249216445408, 0.0014828808589884002, 0.0013060142889163018]
bestperf: [5, 19, 4, 13]
returns: [0.0018723010341177293, 0.0016243358464100854, 0.001299121575506046, 0.0012654725329872551]

Backtesting:  55%|█████▌    | 3100/5602 [00:25<00:21, 118.56it/s]

bestperf: [18, 5, 3, 23]
returns: [0.001811186207729909, 0.0017050956855289012, 0.0015714196453886498, 0.0012922887937520944]
bestperf: [18, 8, 5, 11]
returns: [0.001810425392219539, 0.0010828715575184056, 0.0010073899392242236, 0.0008367518145988573]

Backtesting:  56%|█████▌    | 3140/5602 [00:25<00:21, 114.51it/s]

bestperf: [18, 6, 1, 0]
returns: [0.0019395372476105344, 0.0011659791598996883, 0.001006242196236462, 0.0009553410217959524]

Backtesting:  56%|█████▋    | 3165/5602 [00:25<00:21, 111.51it/s]

bestperf: [1, 6, 9, 8]
returns: [0.0009101290290198794, 0.0006922535915603323, 0.0006369791117326606, 0.0006258811288655242]

Backtesting:  57%|█████▋    | 3190/5602 [00:26<00:21, 111.13it/s]

bestperf: [19, 1, 10, 16]
returns: [0.0026190901422034063, 0.001822691541607968, 0.0017472879253179752, 0.0016828652225746588]

Backtesting:  57%|█████▋    | 3216/5602 [00:26<00:20, 115.09it/s]

bestperf: [16, 19, 10, 8]
returns: [0.0017277226007017532, 0.0015539509125137574, 0.0012665232364048595, 0.0012587416161335963]
bestperf: [18, 16, 12, 19]
returns: [0.002669683632111397, 0.0025576325522400634, 0.002333606313500436, 0.0022603651930199753]

Backtesting:  58%|█████▊    | 3258/5602 [00:26<00:18, 124.58it/s]

bestperf: [6, 16, 5, 22]
returns: [0.0018002692231333661, 0.0015476434956378515, 0.0013810219494989617, 0.0012021653509908248]
bestperf: [22, 6, 8, 20]
returns: [0.0021843205912914776, 0.002169610566211677, 0.0019516236931163, 0.0015610275789077477]

Backtesting:  59%|█████▉    | 3300/5602 [00:27<00:18, 126.52it/s]

bestperf: [6, 22, 5, 8]
returns: [0.001990233090460869, 0.001518913817725176, 0.0013845183711105324, 0.0011581417610155853]
bestperf: [8, 7, 0, 1]
returns: [0.0008736482095803577, 0.0007890294031360767, 0.0007174756717536201, 0.000712084036490479]

Backtesting:  60%|█████▉    | 3355/5602 [00:27<00:17, 127.83it/s]

bestperf: [7, 15, 6, 8]
returns: [0.0012131504912442637, 0.0005210317415558219, 0.0005209109975756743, 0.000490919556520808]
bestperf: [7, 15, 6, 0]
returns: [0.0012818154025628914, 0.0008756476210463049, 0.0008103903985940963, 0.000788277107692581]

Backtesting:  61%|██████    | 3396/5602 [00:27<00:17, 123.72it/s]

bestperf: [6, 20, 0, 4]
returns: [0.0006019283086906579, -0.00020693981067287925, -0.00022120947967763094, -0.0002277852804667413]
bestperf: [10, 6, 4, 12]
returns: [0.000255554410786063, -3.040980048063524e-05, -7.874851958267204e-05, -0.0003354345284097837]

Backtesting:  61%|██████▏   | 3437/5602 [00:28<00:17, 126.83it/s]

bestperf: [18, 0, 6, 4]
returns: [0.0009168712740876828, 0.0009065523266928999, 0.0007968250059551263, 0.0007861308914203224]
bestperf: [18, 0, 22, 11]
returns: [0.0023218012735248816, 0.0021570787727771545, 0.001563902413933782, 0.0014038592521370408]

Backtesting:  62%|██████▏   | 3493/5602 [00:28<00:15, 133.24it/s]

bestperf: [18, 0, 2, 17]
returns: [0.0020085609182496356, 0.001881779052899324, 0.0015533123227922108, 0.001452402780625528]
bestperf: [13, 10, 17, 4]
returns: [0.0011178050460216582, 0.000907295527772245, 0.0005738453200949678, -2.2242037648445567e-05]

Backtesting:  63%|██████▎   | 3534/5602 [00:28<00:16, 123.36it/s]

bestperf: [13, 10, 17, 23]
returns: [0.001803631706418063, 0.001672598796357283, 0.0008498945896635579, 0.0003979305831103286]
bestperf: [13, 10, 23, 17]
returns: [0.0019331651951117745, 0.0016929897138087124, 0.001158396382158866, 0.0010923557970794473]

Backtesting:  64%|██████▍   | 3574/5602 [00:29<00:16, 120.53it/s]

bestperf: [6, 12, 14, 3]
returns: [0.0030578624372574748, 0.0026019721484766833, 0.002346176408523304, 0.002323010734287978]

Backtesting:  64%|██████▍   | 3603/5602 [00:29<00:16, 123.92it/s]

bestperf: [3, 8, 14, 23]
returns: [0.0015715930538469092, 0.0013692000460734377, 0.00135388158662475, 0.0011824565811120458]
bestperf: [18, 23, 8, 3]
returns: [0.0013962578066892828, 0.0013158915566109375, 0.0013006527188212935, 0.0012285066648221044]

Backtesting:  65%|██████▌   | 3645/5602 [00:29<00:16, 122.13it/s]

bestperf: [18, 5, 6, 8]
returns: [0.0031761027777030826, 0.0027036458608584724, 0.0012725796037391657, 0.0012432114500466884]

KeyboardInterrupt:

In [170]:
import pandas as pd

money_norm = (final["Money"]/10000000*100) - 100
spx_norm = (final["SPX"]/final["SPX"].iloc[0]*100) - 100

df_plot = pd.DataFrame({
    "Date": final["Date"],
    "Portfolio": money_norm,
    "SPX": spx_norm
}).melt(id_vars="Date", var_name="Série", value_name="Évolution en %")

fix = px.line(
    df_plot,
    x="Date",
    y="Évolution en %",
    color="Série",
    color_discrete_map={"SPX": "red", "Portfolio": "green"},
    title="Comparaison des évolutions en %"
)

fix.update_layout(hovermode="x unified")
fix.show()

In [151]:
#TESTING PURPOSES

#Returns=GetReturn(df,"2020-05-11",lookback=180000)
#ReturnsSPX=GetReturnSPX(df,"2020-05-11",lookback=180)
#Sigma=GetSigma(df,"2020-05-11",lookback=10000)
#Weight=GetWeight(df,"2020-05-11")
#Lambda=GetLambda(df,"2024-01-11",timeofcalculation=3500,RfDf=RfDf)
#PMatrix,TempoQ=GetPMatrix(df,"2020-05-11",lookback=180,proportion=3)
#GetOmega(PMatrix,Sigma,0.2)

In [171]:
AnnualizedDf=final[["Date","SPX","Money"]]
AnnualizedDf['Date'] = pd.to_datetime(AnnualizedDf['Date'])
AnnualizedDf['Year'] = AnnualizedDf['Date'].dt.year



YearList=AnnualizedDf["Year"].unique()
SPXAnnualized=pd.DataFrame(columns=YearList)
StratAnnualized=pd.DataFrame(columns=YearList)



for year in YearList:
  compteurPerYear=0
  for i in AnnualizedDf.index:
    if AnnualizedDf.loc[i,"Year"]==year:
      if compteurPerYear==0:
        SPXAnnualized.loc[compteurPerYear,year]=AnnualizedDf.loc[i,"SPX"]
        StratAnnualized.loc[compteurPerYear,year]=AnnualizedDf.loc[i,"Money"]
      else :
        SPXAnnualized.loc[compteurPerYear,year]=AnnualizedDf.loc[i,"SPX"]/SPXAnnualized.loc[0,year]*100-100
        StratAnnualized.loc[compteurPerYear,year]=AnnualizedDf.loc[i,"Money"]/StratAnnualized.loc[0,year]*100-100
      compteurPerYear+=1

for year in YearList:
  SPXAnnualized.loc[0,year]=SPXAnnualized.loc[0,year]/SPXAnnualized.loc[0,year]*100-100
  StratAnnualized.loc[0,year]=StratAnnualized.loc[0,year]/StratAnnualized.loc[0,year]*100-100



SPXAvg=[]
StratAvg=[]
for i in SPXAnnualized.index:
  sumSPX=0
  sumStrat=0
  for year in SPXAnnualized.columns:
    sumSPX+=SPXAnnualized.loc[i,year]
    sumStrat+=StratAnnualized.loc[i,year]
  SPXAvg.append(sumSPX/len(YearList))
  StratAvg.append(sumStrat/len(YearList))

SPXAnnualized=SPXAnnualized.drop(columns=[2024,2002]) #too much nan
StratAnnualized=StratAnnualized.drop(columns=[2024,2002])

SPXAvg=[]
StratAVG=[]

for i in SPXAnnualized.index:
  sumSPX=0
  sumStrat=0
  for year in SPXAnnualized.columns:
    sumSPX+=SPXAnnualized.loc[i,year]
    sumStrat+=StratAnnualized.loc[i,year]
  SPXAvg.append(sumSPX/len(YearList))
  StratAVG.append(sumStrat/len(YearList))

dff = pd.DataFrame({"Index": (range(len(SPXAvg))),"Portfolio": StratAVG,"SPX": SPXAvg})


fig = px.line(dff, x="Index", y=["SPX","Portfolio"], color_discrete_map={"SPX": "red","Portfolio": "green"})
fig.show()

In [18]:
#risk mesures

In [172]:
def calculate_historical_var_es(df, col_name='Money', confidence_level=0.95):


    returns = df[col_name].pct_change().dropna()

    cutoff = 1 - confidence_level

    var_value = returns.quantile(cutoff)

    worst_returns = returns[returns <= var_value]
    es_value = worst_returns.mean()

    return {
        "confidence_level": confidence_level,
        "VaR": -var_value,
        "ES": -es_value,
        "count_returns": len(returns),
        "count_breaches": len(worst_returns)
    }



def calculate_sharpe_ratio(df, col_name='close', risk_free_rate_annual=0.04):


    returns = (df[col_name] - df[col_name].shift(1)) / df[col_name].shift(1)
    returns = returns.dropna()
    rf_daily = risk_free_rate_annual / 252
    excess_returns = returns - rf_daily

    sharpe_daily = excess_returns.mean() / excess_returns.std()

    sharpe_annualized = sharpe_daily * np.sqrt(252)

    return sharpe_annualized

In [173]:
print("Portfolio Risk Measures:")
print(calculate_historical_var_es(final, 'Money', 0.99))
print(f"Sharpe Ratio: {calculate_sharpe_ratio(final, 'Money', 0.03):.2f}")

print("\nSPX Risk Measures:")
print(calculate_historical_var_es(final, 'SPX', 0.99))
print(f"Sharpe Ratio: {calculate_sharpe_ratio(final, 'SPX', 0.03):.2f}")

Portfolio Risk Measures:
{'confidence_level': 0.99, 'VaR': 0.03358783535873887, 'ES': 0.048682703674008856, 'count_returns': 5601, 'count_breaches': 57}
Sharpe Ratio: 0.43

SPX Risk Measures:
{'confidence_level': 0.99, 'VaR': 0.033922022158894824, 'ES': 0.049716749837314576, 'count_returns': 5601, 'count_breaches': 57}
Sharpe Ratio: 0.35

In [159]:
df2 = final[["Date", "SPX", "Money"]].copy()
df2["Portfolio"] = df2["Money"]
df2.drop(columns="Money", inplace=True)
df2["Date"] = pd.to_datetime(df2["Date"], dayfirst=True)
df2.set_index("Date", inplace=True)

daily_returns = df2.pct_change()
vol_df = daily_returns.groupby(daily_returns.index.year).std() * np.sqrt(252)
print(vol_df)

fig = px.line(vol_df, x=vol_df.index, y=vol_df.columns,
              labels={"value": "Volatilité Annualisée", "index": "Année"},
              title="Comparaison Volatilité Réalisée : SPX vs Portfolio")

fig.show()

           SPX  Portfolio
Date
2002  0.274455   0.192560
2003  0.167721   0.179871
2004  0.108792   0.124366
2005  0.101250   0.125772
2006  0.098614   0.115460
2007  0.156752   0.194870
2008  0.402597   0.309423
2009  0.268101   0.279985
2010  0.177373   0.260946
2011  0.229119   0.225421
2012  0.124948   0.162996
2013  0.108799   0.187794
2014  0.111728   0.179366
2015  0.152232   0.173996
2016  0.128668   0.142934
2017  0.065718   0.155294
2018  0.167206   0.245003
2019  0.122502   0.143689
2020  0.338334   0.439851
2021  0.128730   0.211922
2022  0.237508   0.206666
2023  0.128406   0.135188
2024  0.111449   0.185453

In [160]:
import pandas as pd
import numpy as np
import plotly.express as px

df2 = final[["Date", "SPX", "Money"]].copy()
df2["Portfolio"] = df2["Money"]
df2.drop(columns="Money", inplace=True)
df2["Date"] = pd.to_datetime(df2["Date"], dayfirst=True)
df2.set_index("Date", inplace=True)

daily_returns = df2.pct_change()
daily_returns.dropna(inplace=True)

daily_returns["annualizedVolSPX"] = daily_returns['SPX'].rolling(window=252).std() * np.sqrt(252)
daily_returns["annualizedVolPf"] = daily_returns['Portfolio'].rolling(window=252).std() * np.sqrt(252)
data_to_plot = daily_returns.dropna()

fig = px.line(data_to_plot,
              x=data_to_plot.index,
              y=["annualizedVolSPX", "annualizedVolPf"],
              labels={"value": "annualized vol", "variable": "Actif", "Date": "Date"},
              title="annualized vol : SPX vs Portfolio")

fig.show()

In [24]:
#multiple runs on variable start date :

numberofdays = 2
all_results = []

for i in range(numberofdays):
    current_start = 181 + i
    results_df = Backtester(dfbacktest, hold=hold, hist=hist, proportion=proportion,
                            df_toBL=df, RfDf=RfDf, confidence2=confidence,
                            proportion2=proportion, tau2=tau, Lambda2=Lambda,
                            start=current_start,modifiedlambda=0)

    money_norm = (results_df["Money"] / 10_000_000 * 100) - 100
    temp_df = pd.DataFrame({f"Iter_{i}": money_norm.values})

    dateresults = results_df["Date"]
    temp_df.index = dateresults

    all_results.append(temp_df)


global_df = pd.concat(all_results, axis=1)
global_df_clean = global_df.dropna()
print(global_df_clean.head())

Backtesting: 100%|██████████| 5602/5602 [00:30<00:00, 183.78it/s]
Backtesting: 100%|██████████| 5601/5601 [00:30<00:00, 184.30it/s]

            Iter_0  Iter_1
Date
2002-09-12     0.0     0.0
2002-09-13     0.0     0.0
2002-09-16     0.0     0.0
2002-09-17     0.0     0.0
2002-09-18     0.0     0.0

In [26]:
global_df_clean

                Iter_0      Iter_1
Date
2002-09-12    0.000000    0.000000
2002-09-13    0.000000    0.000000
2002-09-16    0.000000    0.000000
2002-09-17    0.000000    0.000000
2002-09-18    0.000000    0.000000
...                ...         ...
2024-02-23  700.258166  611.183934
2024-02-26  698.687244  610.004753
2024-02-27  700.653847  611.683283
2024-02-28  699.430653  610.566525
2024-02-29  699.430653  610.566525

[5601 rows x 2 columns]

In [27]:
#add spx to compare

dfcopyfinal = final[["Date", "SPX"]].copy()
dfcopyfinal.index=dfcopyfinal["Date"]
dfcopyfinal.drop(columns="Date", inplace=True)

global_df_clean = global_df_clean.merge(dfcopyfinal,left_index=True,right_index=True,how="left")
spx_norm = (global_df_clean["SPX"]/global_df_clean["SPX"].iloc[0]*100) - 100
global_df_clean["SPX"] = spx_norm

In [28]:
global_df_clean

                Iter_0      Iter_1         SPX
Date
2002-09-12    0.000000    0.000000    0.000000
2002-09-13    0.000000    0.000000    0.326978
2002-09-16    0.000000    0.000000    0.472427
2002-09-17    0.000000    0.000000   -1.509736
2002-09-18    0.000000    0.000000   -1.967505
...                ...         ...         ...
2024-02-23  700.258166  611.183934  473.767350
2024-02-26  698.687244  610.004753  471.594638
2024-02-27  700.653847  611.683283  472.569934
2024-02-28  699.430653  610.566525  471.620570
2024-02-29  699.430653  610.566525  471.620570

[5601 rows x 3 columns]

In [33]:
import numpy as np
import plotly.graph_objects as go


def animate_dataframe_plotly(df,step=5,speed=40,spx_col="SPX"):

    df_anim = df.iloc[::step]
    x = df_anim.index

    final_values = df_anim.iloc[-1]
    best_col = final_values.drop(spx_col, errors="ignore").idxmax()

    traces = []
    for col in df_anim.columns:
        if col == spx_col:
            color = "red"
            width = 2
            alpha = 1
        elif col == best_col:
            color = "green"
            width = 2
            alpha = 1
        else:
            color = "rgba(250, 250, 250,1)"
            width = 1
            alpha = 0.4
        traces.append(go.Scatter(x=[],y=[],mode="lines",line=dict(color=color, width=width),opacity=alpha,name=col,showlegend=False))

    frames = []
    for t in range(1, len(df_anim)):
        frame_data = []
        for col in df_anim.columns:
            frame_data.append(go.Scatter(x=x[:t],y=df_anim[col].values[:t]))
        frames.append(go.Frame(data=frame_data, name=str(t)))

    layout = go.Layout(title="Multiple Backtest Runs",xaxis=dict(title="Date"),yaxis=dict(title="Perf (%)"),plot_bgcolor="black",paper_bgcolor="black",font=dict(color="white"),updatemenus=[dict(type="buttons",showactive=False,buttons=[dict(label="▶ Play",method="animate",args=[None,dict( frame=dict(duration=speed, redraw=True),fromcurrent=True)]),dict(label="⏸ Pause",method="animate",args=[[None],dict(frame=dict(duration=0), mode="immediate")])])])

    fig = go.Figure(data=traces,layout=layout,frames=frames)

    fig.show()


#animate_dataframe_plotly(global_df_clean,step=5,speed=20)

In [34]:
import plotly.express as px

fig = px.line(
    global_df_clean,
    title=f"Comparaison des {numberofdays} itérations de Backtest (Rolling)",
    labels={
        "index": "Date",
        "value": "Performance Normalisée (%)",
        "variable": "Scénario"
    },
    template="plotly_dark"
)

fig.update_traces(line=dict(width=1.5))

if "SPX_Benchmark" in global_df_clean.columns:
    fig.update_traces(
        selector={"name": "SPX_Benchmark"},
        line=dict(width=4, color="white", dash="dot")
    )

fig.show()

Excess: 0.08824333617258762  Var: 0.02788159831970587  Vol: 0.1669778378100096  λ: 3.1649310473790124  Sharpe: 0.5284733431091165

In [39]:
#modified lambda evolution

#multiple runs on variable start date :

numberofruns = 5
all_results = []
factor=0.1
for i in range(numberofruns):
    results_df = Backtester(dfbacktest, hold=hold, hist=hist, proportion=proportion,
                            df_toBL=df, RfDf=RfDf, confidence2=confidence,
                            proportion2=proportion, tau2=tau, Lambda2=Lambda,
                            start=181,modifiedlambda=-i*factor)

    money_norm = (results_df["Money"] / 10_000_000 * 100) - 100
    temp_df = pd.DataFrame({f"Iter_{i}": money_norm.values})

    dateresults = results_df["Date"]
    temp_df.index = dateresults

    all_results.append(temp_df)


global_df = pd.concat(all_results, axis=1)
global_df_clean = global_df.dropna()
print(global_df_clean.head())

Backtesting: 100%|██████████| 5602/5602 [00:32<00:00, 171.35it/s]
Backtesting: 100%|██████████| 5602/5602 [00:36<00:00, 155.53it/s]
Backtesting: 100%|██████████| 5602/5602 [00:36<00:00, 152.64it/s]
Backtesting: 100%|██████████| 5602/5602 [00:32<00:00, 170.27it/s]
Backtesting: 100%|██████████| 5602/5602 [00:31<00:00, 178.85it/s]

            Iter_0  Iter_1  Iter_2  Iter_3  Iter_4
Date
2002-09-11     0.0     0.0     0.0     0.0     0.0
2002-09-12     0.0     0.0     0.0     0.0     0.0
2002-09-13     0.0     0.0     0.0     0.0     0.0
2002-09-16     0.0     0.0     0.0     0.0     0.0
2002-09-17     0.0     0.0     0.0     0.0     0.0

In [40]:
dfcopyfinal = final[["Date", "SPX"]].copy()
dfcopyfinal.index=dfcopyfinal["Date"]
dfcopyfinal.drop(columns="Date", inplace=True)

global_df_clean = global_df_clean.merge(dfcopyfinal,left_index=True,right_index=True,how="left")
spx_norm = (global_df_clean["SPX"]/global_df_clean["SPX"].iloc[0]*100) - 100
global_df_clean["SPX"] = spx_norm

In [41]:
import plotly.express as px

fig = px.line(
    global_df_clean,
    title=f"Comparaison des {numberofdays} itérations de Backtest (Rolling)",
    labels={
        "index": "Date",
        "value": "Performance Normalisée (%)",
        "variable": "Scénario"
    },
    template="plotly_dark"
)

fig.update_traces(line=dict(width=1.5))

if "SPX_Benchmark" in global_df_clean.columns:
    fig.update_traces(
        selector={"name": "SPX_Benchmark"},
        line=dict(width=4, color="white", dash="dot")
    )

fig.show()

In [248]:
#perfect views

def PerfectView(df,date,space=21): #match start and date and space with the holding time (1mo = 21)
    date=pd.to_datetime(date)
    copydf=df.copy()
    copydf=copydf[copydf["Date"] >= date]
    for i in range(0,copydf.shape[0]):
        if i%space!=0:
            copydf.iloc[i,1]=np.nan

    copydf.dropna(inplace=True)
    datelist=copydf["Date"]
    copydf.drop(columns="Date", inplace=True)
    copydf = (copydf/ copydf.shift(1)) ** (1/space)-1
    copydf.dropna(inplace=True)
    if copydf.shape[0]!=0:
        views= copydf.iloc[0, :]
        views=views.to_list()
        spxreturns=views[0]
        views.pop(0)
        listofreturns=[]
        for i in range(len(views)):
            listofreturns.append((views[i],i))
    else :
        print("LAST RUN SO NO PREDICTION")
        listofreturns=[(0,0),(0,1),(0,2),(0,3)]
        spxreturns=0
    listofreturns.sort(reverse=True)
    listofreturns=listofreturns[0:4:1] #MODIFIER LA PROPORTION AU BESOIN ICI
    return listofreturns,spxreturns




def ModifiedBlackPerfectViews(backtestStartDate, rebalancingFrequency, lookbackPeriod, df,RfDf,confidence=0.75,proportion=4,tau=0.025,Lambda=3,historical_returns=0,modifiedlambda=0):
    #implement the full backtest of the black and litterman model

    #---------
    #PARAMETERS
    #---------
    datetoremove=pd.to_datetime("2018-04-06") #add date to remove
    listofbanneddays=[]
    Sigma=get_shrunk_covariance(df,backtestStartDate,lookback=60) #using 720 days to have better sigma of 2 years
    Sigma=getSigmaModified(df,backtestStartDate,lookback=60,listofbanneddays=listofbanneddays) #using 720 days to have better sigma of 2 years

    PMatrix=np.zeros((proportion,24))
    Q=np.zeros((proportion,1))



    bestperf,perfmarket=PerfectView(df,backtestStartDate,21)


    for lineview in range(len(bestperf)):
        for i in range(24):
            PMatrix[lineview,i]=-1/24
        PMatrix[lineview,bestperf[lineview][1]]=1-1/24

    for views in range(len(bestperf)):
        Q[views,0]=(bestperf[views][0]-perfmarket)

    Omega=GetOmega(PMatrix, Sigma, c=confidence)
    rf=GetRiskFree(df,backtestStartDate,lookbackPeriod,RfDf)
    weights = GetWeight(df, backtestStartDate)
    weights = np.array(weights).reshape(-1, 1)

    changingLambda=True
    if changingLambda==True:
        if pd.to_datetime(backtestStartDate) < pd.to_datetime("2006-04-06"):
            Lambda=3
        else :
            Lambda=3#+0.1*GetLambda(df,backtestStartDate,timeofcalculation=504,RfDf=RfDf)
    else :
        Lambda=3

    uimplied = Lambda * (Sigma @ weights) + rf
    #BL formula
    #tau=OmegaLinked




    optimizedReturn=(np.linalg.inv(np.linalg.inv(tau*Sigma)+np.transpose(PMatrix)@np.linalg.inv(Omega)@PMatrix)) @ (np.linalg.inv(tau*Sigma)@uimplied+np.transpose(PMatrix)@np.linalg.inv(Omega)@Q)
    LambdaMarkowitz=3

    #MarkowitzAllocation
    WeightBL=np.linalg.inv(Sigma)@(optimizedReturn-rf)/LambdaMarkowitz
    WeightRF=1-np.sum(WeightBL)
    #if not np.isclose(float(np.sum(WeightBL)), 1.0, atol=1e-6):
        #print(np.sum(WeightBL))
        #raise ValueError("Weights do not sum to 1, please investigate.")

    return WeightBL,WeightRF,historical_returns


ModifiedBlackPerfectViews("2018-05-11", rebalancingFrequency=3, lookbackPeriod=180, df=df,RfDf=RfDf)

(           0
 0  -0.153577
 1  -0.153577
 2  -0.153577
 3  -0.153577
 4  -0.153577
 5  -0.153577
 6   1.144955
 7  -0.153577
 8  -0.153577
 9  -0.153577
 10 -0.153577
 11 -0.153577
 12 -0.153577
 13 -0.153577
 14 -0.153577
 15 -0.153577
 16 -0.153577
 17  0.899139
 18 -0.153577
 19 -0.153577
 20 -0.153577
 21  0.383425
 22  1.644017
 23 -0.153577,
 0   -1.416645e-13
 dtype: float64,
 0)

In [249]:
from rich.console import Console
from rich.panel import Panel
from tqdm import tqdm

console = Console()

#BACK TESTER
dfbacktest=df.copy()
dfbacktest["Date"] = pd.to_datetime(df["Date"], format="%d/%m/%Y")
dfbacktest["MonthIndex"] = dfbacktest["Date"].dt.to_period("M")

df_length = dfbacktest.shape[1] - 2  # bcs of date and spx
last_rebalance = dfbacktest.loc[0, "Date"]  # première date
month_count = 0

# 🎨 AFFICHAGE STYLÉ (sans prompts)
hold = 1
hist = 0
proportion = 4
Lambda=3
tau=0.025
confidence=0.75

console.print(Panel.fit(
    "[bold cyan]📊 PORTFOLIO BACKTESTER[/bold cyan]\n"
    "[dim]Black-Litterman Model[/dim]",
    border_style="cyan"
))

console.print(f"\n[yellow]⚙️  Configuration :[/yellow]")
console.print(f"   • Hold period: [cyan]{hold}[/cyan] mois")
console.print(f"   • Historique: [cyan]{hist}[/cyan] mois")
console.print(f"   • Proportion: [cyan]{proportion}[/cyan]")
console.print(f"   • Lambda: [cyan]{Lambda:.4f}[/cyan]")
console.print(f"   • Confiance: [cyan]{confidence}[/cyan]")
console.print(f"   • Taux: [cyan]{tau}[/cyan]\n")

console.print("\n[yellow]⏳ Lancement du backtest...[/yellow]\n")

def Backtester(df,hold, hist, proportion,df_toBL, RfDf,confidence2,proportion2,tau2,Lambda2,start,modifiedlambda):
    #new dataframe for stock quantity

    StockQty = df.copy()
    StockQty.drop(columns="MonthIndex", inplace=True)
    historical_returns=[]

    StockQty.loc[:, :] = 0
    #starting data
    MoneyAtStart = 10000000
    month_count=0
    CurrentValue=MoneyAtStart
    spaceindays=0
    #first ligne
    StockQty.loc[start, "Money"] = MoneyAtStart
    StockQty.loc[start, "SPX"] = df.iloc[start, 1]
    StockQty.loc[start, "Date"] = df.iloc[start, 0]
    RiskFreeAmount=0
    #start of the algorithm

    for i in tqdm(range(start,df.shape[0]), desc="Backtesting"):
      StockQty.iloc[i,0]=df.iloc[i,0]
      StockQty.iloc[i,1]=df.iloc[i,1]
      fees=0


      if df.loc[i, "Date"].month != df.loc[i-1, "Date"].month:
        month_count += 1


    # Si on atteint la période voulue
      if i>= hist and spaceindays>21*hold:
        #print(f"🔁 Rebalancement déclenché à la date : {df.loc[i, 'Date'].date()}")
        #print(str(df.iloc[i,0]))

        spaceindays=0

        BLWeight,RiskFreeAmount,historical_returns=ModifiedBlackPerfectViews(str(df.iloc[i,0]),3,3*22,df_toBL,RfDf,confidence=confidence2,proportion=proportion2,tau=tau2,Lambda=Lambda2,historical_returns=historical_returns,modifiedlambda=modifiedlambda)
        #print(len(BLWeight))
        for index in range(len(BLWeight)):
            StockQty.iloc[i,index+2]=(BLWeight.iloc[index,0]*CurrentValue)/df.iloc[i,index+2] #qty = weight*total value/price
      else :
        spaceindays+=1
        for stocks in range(2,StockQty.shape[1]-1):
          StockQty.iloc[i,stocks]=StockQty.iloc[i-1,stocks] #same qty


      #value of pf

      GainOrLoss = 0
      for stocks in range(2, StockQty.shape[1]-1):
        qty = StockQty.iloc[i, stocks]

        if qty != 0.0:
            price_now = df.iloc[i, stocks]
            price_prev = df.iloc[i-1, stocks]
            GainOrLoss += qty * (price_now - price_prev)

      daily_rate = GetRiskFree(df, str(df.iloc[i,0]), 1, RfDf)
      interest_gain = (CurrentValue * RiskFreeAmount) * daily_rate
      CurrentValue += GainOrLoss + interest_gain - fees
      StockQty.iloc[i,-1]=CurrentValue


    StockQty = StockQty.iloc[start:].reset_index(drop=True)
    return StockQty
RfDf=GetRfDataframe(df)
final = Backtester(dfbacktest, hold=hold, hist=hist, proportion=proportion, df_toBL=df,RfDf=RfDf,confidence2=confidence,proportion2=proportion,tau2=tau,Lambda2=Lambda,start=181,modifiedlambda=0)

console.print("\n[green]✅ Backtest terminé avec succès ![/green]\n")

╭─────────────────────────╮
│ 📊 PORTFOLIO BACKTESTER │
│ Black-Litterman Model   │
╰─────────────────────────╯

⚙️  Configuration :

   • Hold period: 1 mois

   • Historique: 0 mois

   • Proportion: 4

   • Lambda: 3.0000

   • Confiance: 0.75

   • Taux: 0.025

⏳ Lancement du backtest...

Backtesting: 100%|██████████| 5602/5602 [01:54<00:00, 49.12it/s]

LAST RUN SO NO PREDICTION

✅ Backtest terminé avec succès !

In [250]:
import pandas as pd

money_norm = (final["Money"]/10000000*100) - 100
spx_norm = (final["SPX"]/final["SPX"].iloc[0]*100) - 100

df_plot = pd.DataFrame({
    "Date": final["Date"],
    "Portfolio": money_norm,
    "SPX": spx_norm
}).melt(id_vars="Date", var_name="Série", value_name="Évolution en %")

fix = px.line(
    df_plot,
    x="Date",
    y="Évolution en %",
    color="Série",
    color_discrete_map={"SPX": "red", "Portfolio": "green"},
    title="Comparaison des évolutions en %"
)

fix.update_layout(hovermode="x unified")
fix.show()

In [251]:
import pandas as pd
import numpy as np
import plotly.express as px

df2 = final[["Date", "SPX", "Money"]].copy()
df2["Portfolio"] = df2["Money"]
df2.drop(columns="Money", inplace=True)
df2["Date"] = pd.to_datetime(df2["Date"], dayfirst=True)
df2.set_index("Date", inplace=True)

daily_returns = df2.pct_change()
daily_returns.dropna(inplace=True)

daily_returns["annualizedVolSPX"] = daily_returns['SPX'].rolling(window=252).std() * np.sqrt(252)
daily_returns["annualizedVolPf"] = daily_returns['Portfolio'].rolling(window=252).std() * np.sqrt(252)
data_to_plot = daily_returns.dropna()

fig = px.line(data_to_plot,
              x=data_to_plot.index,
              y=["annualizedVolSPX", "annualizedVolPf"],
              labels={"value": "annualized vol", "variable": "Actif", "Date": "Date"},
              title="annualized vol : SPX vs Portfolio")

fig.show()